name: PExChat
main: com.voidteam.PExChat.Main
version: 4.0
depend: [PermissionsEx]
author: jacklink01
description: Based on Sleelin's PexChat and Drakia's iChat.
commands:
  pexchat:
    description: Used to reload the plugin.
    usage: /<command> reload - Used to reload the plugin.